import React from 'react';
import { Metadata } from 'next';
import { AuditResults } from '@/components/AuditResults';
import { notFound } from 'next/navigation';

export async function generateMetadata({ params }: { params: { id: string } }): Promise<Metadata> {
  try {
    const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL || 'http://127.0.0.1:3001'}/api/audit/${params.id}`);
    if (!res.ok) throw new Error('Not found');
    const audit = await res.json();

    const savings = audit.potentialAnnualSavings.toLocaleString();
    
    return {
      title: `AI Spend Audit | Found $${savings} in Savings`,
      description: `We just analyzed this team's AI tool stack and found $${savings} in potential annual savings. Run your own audit in 60 seconds.`,
      openGraph: {
        title: `AI Spend Audit | Found $${savings} in Savings`,
        description: `We just analyzed this team's AI tool stack and found $${savings} in potential annual savings. Run your own audit in 60 seconds.`,
        images: ['/og-image.png'],
        type: 'website'
      },
      twitter: {
        card: 'summary_large_image',
        title: `AI Spend Audit | Found $${savings} in Savings`,
        description: `We just analyzed this team's AI tool stack and found $${savings} in potential annual savings.`,
      }
    };
  } catch (e) {
    return {
      title: 'SpendLens | Public AI Audit'
    };
  }
}

export default async function PublicAuditPage({ params }: { params: { id: string } }) {
  const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL || 'http://127.0.0.1:3001'}/api/audit/${params.id}`, { cache: 'no-store' });
  
  if (!res.ok) {
    notFound();
  }

  const audit = await res.json();

  return (
    <main className="min-h-screen bg-background bg-dot-pattern py-20">
      <div className="max-w-4xl mx-auto px-6 text-center mb-12">
        <h1 className="text-4xl font-black tracking-tight mb-4">Public Audit Report</h1>
        <p className="text-lg text-muted-foreground">
          This is a verified AI spend audit generated by SpendLens.
        </p>
      </div>

      <div className="px-6">
        <AuditResults results={audit} />
      </div>

      <div className="text-center mt-12">
        <a 
          href="/" 
          className="inline-flex bg-primary text-primary-foreground px-6 py-3 rounded-xl font-bold hover:bg-primary/90 transition-colors"
        >
          Run your own AI Audit
        </a>
      </div>
    </main>
  );
}
